-- phpMyAdmin SQL Dump
-- version 4.0.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Aug 20, 2013 at 11:11 PM
-- Server version: 5.5.24
-- PHP Version: 5.3.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `rippletechyowl`
--

-- --------------------------------------------------------

--
-- Table structure for table `charities`
--

CREATE TABLE IF NOT EXISTS `charities` (
  `id` int(20) NOT NULL AUTO_INCREMENT,
  `title` varchar(2000) NOT NULL,
  `description` varchar(2000) NOT NULL,
  `url` varchar(2000) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=17 ;

--
-- Dumping data for table `charities`
--

INSERT INTO `charities` (`id`, `title`, `description`, `url`) VALUES
(1, 'Bead For Life', 'BeadsforLife sponsors Community Development projects in health, vocational training for impoverished youth, affordable housing, and business development. These projects are financed with the net profits from the sale of the beads and shea butter products and support not only our members, but other impoverished people living in Uganda. Our members are women of Kampala and Iganga make beautiful handcrafted paper beads form recycled paper and turn them into jewelry.', 'beadforlife'),
(2, 'Brilliant Earth', 'Our goal at Brilliant Earth is to make jewelry as beautiful as it can be. We are passionate about cultivating a more ethical, transparent, and sustainable jewelry industry. Brilliant Earth believes that luxury goods need not come at great human or environmental cost. We donate 5 percent of our profits to help communities who have suffered from unethical practices in the jewelry industry. We strive to create a long-term and sustainable approach to community development.', 'brilliantearth'),
(3, 'Bullets 2 Bandages', 'Bullets to Bandages is a mission-driven, socially conscious apparel and accessories and unique company designed to give thanks to veterans, those fighting for our country, and the families who provide them with love and support at home. Our line of Accessories and the Unique are all made in America from once fired bullets. We chose the bullet because it grabs a person''s attention and ignites an important conversation about "saying thank you to veterans."', 'bullets2bandages'),
(4, 'Cangles', 'Cangles is a Michigan family business that makes unique handmade recycled jewelry and gifts. When you make a purchase of our recycled jewelry, a portion is donated to charities that help the environment or provide services to people in need, and their pets. Save the Earth Foundation, Wounded Warrior Project, Pet FriendZ, Autism Speaks, our community food pantry, and Susan G. Komen for the Cure are included.', 'cangles'),
(5, 'Charity Charms', 'Charity Charms helps many different varieties of Organizations to raise funds and awareness. Sterling Silver "Clip On" charms are made to enhance any Charm Bracelet or Necklace. Grouped by theme, you can create a whole bracelet of crosses, hearts, animals or a mixture of what means the most to your cause. Or create a Custom Logo Charm for your charity for a unique item that your supporters will love.', 'charitycharms'),
(6, 'Falling Whistles', 'Falling Whistle is a campaign for peace in the Congo. We sale whistles as a symbol of protest.', 'fallingwhistles'),
(7, 'Flex Watches', 'Every color represents a different charity that we’ve partnered with to give back 10 percent. Flex Watches was created to inspire change and is changing the watch industry one watch at a time. The Flex is not just a watch, it’s a brand that represents the lifestyle we aspire to lead. The 10 10 10 standard (10 colors, 10 charities, 10 percent) was created in hopes of raising awareness through unique colorful products. Our watches don''t just tell time, they tell stories.', 'flexwatches'),
(9, 'John Hardy', 'In 2006, John Hardy launches its "Sustainable Advertising" program to offset the carbon emissions from its print advertising, business travel and electricity consumption. By planting bamboo on Bali and Nusa Penida, a small island off the coast of Bali. Through its "Wear Bamboo, Plant Bamboo" program, a portion of the proceeds from the sale of its Bamboo collection items are used to fund the company''s continuous bamboo plantings.', 'johnhardy'),
(10, 'Hands For Africa', 'Hands For Africa''s mandate is restoring lost hope to innocent victims of civil wars in African countries and to develop and implement programs that foster self-reliance by directly engaging the innocent victims and their communities to provide artificial limbs for amputees, wells for clean water, agricultural development, educational scholarships for the innocent victims and their children, medical and health care support, micro finance loans for trade and housing through community construction.', 'handsforafrica'),
(11, 'Newspaper Jewelry', 'Newspaper Jewelry features eco jewelry including unique cufflinks, eco friendly gifts for women, and eco friendly gifts for men, consisting of recycled newspaper, expired coupons, dollar bills, losing lottery tickets and sweetener packets.', 'newspaperjewelry'),
(12, 'Not For Sale', 'Not For Sale creates futures for survivors of modern day slavery through intentional economic empowerment. They showcase products made by survivors of human trafficking and those vulnerable to exploitation. Each purchase from the Not For Sale Store generates funding that supports the creation of new futures for survivors of human trafficking and vulnerable communities.', 'notforsale'),
(13, 'Night Light', 'Our local offices build relationships with victims of commercial sexual exploitation and those who are at risk and provide hope, intervention, rescue, and assistance by offering alternative vocational opportunities, life skills training, and physical, emotional, and spiritual development to those seeking freedom. NightLight builds support networks internationally to intervene and assist women, men, and children whose lives are negatively impacted by the sex industry.', 'nightlight'),
(14, 'Project Have Hope', 'Project Have Hope works with a group of 100 women in the Acholi Quarter of Uganda and helps them transform their lives and the lives of their families. Through the sale of their beautiful, handmade paper bead jewelry, the women can feed their families, send their children to school, and look forward to a richer future.', 'projecthavehope'),
(15, 'Shawn Warren', 'Shawn Warren''s main visions was to take fine jewelry our of the realm of impossibility. With this goal in mind, she designed her first collection of vintage-inspired 18K gold earrings with precious and semi-precious stones smartly priced at $2,500 per pair. Shawn Warren has always believed in giving back. Every year a portion of her sales are donated to charity. Shawn donates 10 percent of all sales to inner city children, cancer and animal-related charities.', 'shawnwarren'),
(16, 'WeWood', 'WeWOOD lets us rediscover nature in its beauty, its simplicity and inspired design. It reminds us of a tree''s powerful way of life; rooted, yet reaching. Completely absent of artificial and toxic materials, the WeWOOD Timepiece is as natural as your wrist. One Timepiece plants one tree, and together we help to ensure the health and survival of the natural world. One Watch One Tree One Planet', 'wewood');

-- --------------------------------------------------------

--
-- Table structure for table `jewelry`
--

CREATE TABLE IF NOT EXISTS `jewelry` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `gender` tinytext NOT NULL,
  `type` varchar(300) NOT NULL,
  `image` varchar(1000) NOT NULL,
  `cart` varchar(1000) NOT NULL,
  `price` varchar(100) NOT NULL,
  `description` varchar(120) NOT NULL,
  `title` varchar(70) NOT NULL,
  `charity` varchar(100) NOT NULL,
  `promo` varchar(3) NOT NULL,
  `note` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=240 ;

--
-- Dumping data for table `jewelry`
--

INSERT INTO `jewelry` (`id`, `date`, `gender`, `type`, `image`, `cart`, `price`, `description`, `title`, `charity`, `promo`, `note`) VALUES
(25, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/105.jpg', 'product=105+-+bracelet+-+Sanyu+Bangle+Bracelet+Red&amp;price=5', '$5.00 ', 'Strung on flexible elastic, a perfect fit for any wrist', 'Sanyu Bangle Bracelet Red', 'Beads for life', '', 0),
(26, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/148.jpg', 'product=148+-+bracelet+-+Black+Bead+and+Paper+Bracelets+&amp;price=12', '$12.00 ', '3 bracelets of recycled paper beads separated by black beads ', 'Black Bead and Paper Bracelets ', 'Project Have Hope', '', 0),
(27, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/101.jpg', 'product=101+-+bracelet+-+Leena+Three+Strand+Bracelet+Brown&amp;price=15', '$15.00 ', '', 'Leena Three Strand Bracelet Brown', 'Beads for life', '', 0),
(28, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/102.jpg', 'product=102+-+bracelet+-+Leena+Three+Strand+Bracelet+Blue&amp;price=15', '$15.00 ', 'Three single strands joined  to create a strong look of a delicate detail.', 'Leena Three Strand Bracelet Blue', 'Beads for life', '', 0),
(29, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/103.jpg', 'product=103+-+bracelet+-+Leena+Three+Strand+Bracelet+Green&amp;price=15', '$15.00 ', 'Three single strands joined  to create a strong look of a delicate detail.', 'Leena Three Strand Bracelet Green', 'Beads for life', '', 0),
(30, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/104.jpg', 'product=104+-+bracelet+-+Leena+Three+Strand+Bracelet+Red&amp;price=15', '$15.00 ', 'Three single strands joined  to create a strong look of a delicate detail', 'Leena Three Strand Bracelet Red', 'Beads for life', '', 0),
(31, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/106.jpg', 'product=106+-+bracelet+-+Zola+Band+Bracelet+Red&amp;price=15', '$15.00 ', '', 'Zola Band Bracelet Red', 'Beads for life', '', 0),
(32, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/107.jpg', 'product=107+-+bracelet+-+Zola+Band+Bracelet+Blue&amp;price=15', '$15.00 ', 'Zola, represent peace in the lives of the people we touch', 'Zola Band Bracelet Blue', 'Beads for life', '', 0),
(33, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/108.jpg', 'product=108+-+bracelet+-+Obi+Band+for+Men&amp;price=15', '$15.00 ', 'The Obi Band for men was created for all the men in our Bead Circle! ', 'Obi Band for Men', 'Beads for life', '', 0),
(34, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/117.jpg', 'product=117+-+bracelet+-+Arizona+Green+Tea+Cuff+Bracelet&amp;price=15', '$15.00 ', 'Handmade by recycling an Arizona Green Tea can.', 'Arizona Green Tea Cuff Bracelet', 'Cangles', '', 0),
(35, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/129.jpg', 'product=129+-+bracelet+-+Cause+and+Health+Band+Red&amp;price=15', '$15.00 ', 'red ribbon: Heart Disease & HIV/AIDS, drunk driving & pro-life', 'Cause and Health Band Red', 'Charity Charms', '', 0),
(36, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/130.jpg', 'product=130+-+bracelet+-+Cause+and+Health+Band+Pink&amp;price=15', '$15.00 ', 'pink ribbon: breast cancer and birth parents', 'Cause and Health Band Pink', 'Charity Charms', '', 0),
(37, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/131.jpg', 'product=131+-+bracelet+-+Cause+and+Health+Band+Orange&amp;price=15', '$15.00 ', 'Diseases: Leukemia, Kidney & Skin Cancers. Causes: Animal Abuse', 'Cause and Health Band Orange', 'Charity Charms', '', 0),
(38, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/132.jpg', 'product=132+-+bracelet+-+Cause+and+Health+Band+Yellow&amp;price=15', '$15.00 ', 'Liver Disease & Bladder cancer, Military Support & Remembrance', 'Cause and Health Band Yellow', 'Charity Charms', '', 0),
(39, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/133.jpg', 'product=133+-+bracelet+-+Cause+and+Health+Band+Green&amp;price=15', '$15.00 ', 'Kidney Disease, Mental Health Disorders', 'Cause and Health Band Green', 'Charity Charms', '', 0),
(40, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/134.jpg', 'product=134+-+bracelet+-+Cause+and+Health+Band+Turquoise&amp;price=15', '$15.00 ', 'Disease: Ovarian & Cervical Cancers. Causes: Addiction Recovery ', 'Cause and Health Band Turquoise', 'Charity Charms', '', 0),
(41, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/135.jpg', 'product=135+-+bracelet+-+Cause+and+Health+Band+Blue&amp;price=15', '$15.00 ', 'Diseases: Colon Cancer, Arthritis & Huntington’s Disease', 'Cause and Health Band Blue', 'Charity Charms', '', 0),
(42, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/136.jpg', 'product=136+-+bracelet+-+Cause+and+Health+Band+Purple&amp;price=15', '$15.00 ', 'Disease: Autism & Cystic Fibrosis, Domestic Violence', 'Cause and Health Band Purple', 'Charity Charms', '', 0),
(43, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/137.jpg', 'product=137+-+bracelet+-+Cause+and+Health+Band+Black&amp;price=15', '$15.00 ', 'black ribbon: Mourning, Gang & Terrorism Prevention ', 'Cause and Health Band Black', 'Charity Charms', '', 0),
(44, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/141.jpg', 'product=141+-+bracelet+-+Leukemia+Awareness+Bracelet&amp;price=15', '$15.00 ', 'Orange signifies both leukemia and kidney cancer awareness', 'Leukemia Awareness Bracelet', 'Project Have Hope', 'yes', 0),
(45, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/142.jpg', 'product=142+-+bracelet+-+Multi-Strand+Paper+Bead+Bracelet&amp;price=15', '$15.00 ', '', 'Multi-Strand Paper Bead Bracelet', 'Project Have Hope', '', 0),
(46, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/143.jpg', 'product=143+-+bracelet+-+Breast+Cancer+Awareness+Bracelet&amp;price=15', '$15.00 ', 'Pink signifies breast cancer awareness', 'Breast Cancer Awareness Bracelet', 'Project Have Hope', '', 0),
(47, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/144.jpg', 'product=144+-+bracelet+-+Ovarian+Cancer+Awareness+Bracelet&amp;price=15', '$15.00 ', 'Teal signifies ovarian cancer awareness. ', 'Ovarian Cancer Awareness Bracelet', 'Project Have Hope', '', 0),
(48, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/145.jpg', 'product=145+-+bracelet+-+All+Cancer+Awareness+Bracelet&amp;price=15', '$15.00 ', 'lavender signifies awareness for all cancers.  ', 'All Cancer Awareness Bracelet', 'Project Have Hope', '', 0),
(49, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/146.jpg', 'product=146+-+bracelet+-+Cervical+Awareness+Bracelet&amp;price=15', '$15.00 ', 'Teal and white signify cervical cancer awareness', 'Cervical Awareness Bracelet', 'Project Have Hope', '', 0),
(50, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/147.jpg', 'product=147+-+bracelet+-+Colon+Cancer+Awareness+Bracelet&amp;price=15', '$15.00 ', 'Dark blue signifies colon cancer awareness', 'Colon Cancer Awareness Bracelet', 'Project Have Hope', '', 0),
(51, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/149.jpg', 'product=149+-+bracelet+-+Bangle+Bracelet&amp;price=15', '$15.00 ', 'Made from recycled paper. Each is handmade using different colors ', 'Bangle Bracelet', 'Project Have Hope', '', 0),
(52, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/150.jpg', 'product=150+-+bracelet+-+Kidney+Cancer+Awareness+Bracelet&amp;price=15', '$15.00 ', 'Orange signifies both kidney cancer and leukemia cancer awareness', 'Kidney Cancer Awareness Bracelet', 'Project Have Hope', '', 0),
(53, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/151.1.jpg', 'product=151+-+bracelet+-+Memory+Wire+Glass+Bead+Bracelet&amp;price=15', '$15.00 ', 'made of recycled glass, bone, clay, amber and stone beads', 'Memory Wire Glass Bead Bracelet', 'Project Have Hope', '', 0),
(54, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/152.jpg', 'product=152+-+bracelet+-+Paper+Bead+and+Fabric+Bracelet&amp;price=15', '$15.00 ', 'Recycled paper beads are strung with African fabric twisted around it. ', 'Paper Bead and Fabric Bracelet', 'Project Have Hope', '', 0),
(55, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/113.jpg', 'product=113+-+bracelet+-+Brisk+Tea+Bangle&amp;price=16.95', '$16.95 ', 'Brisk Tea bangle, eco-fashionable American-made accessory', 'Brisk Tea Bangle', 'Cangles', '', 0),
(56, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/112.jpg', 'product=112+-+bracelet+-+Arizona+Green+Tea+Lemonade+Bangle&amp;price=17.95', '$17.95 ', 'bangle is handmade by recycling Arizona Green Tea Lemonade', 'Arizona Green Tea Lemonade Bangle', 'Cangles', '', 0),
(57, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/116.jpg', 'product=116+-+bracelet+-+Arizona+Green+Tea+Bangle&amp;price=17.95', '$17.95 ', 'Bangle is handmade by recycling Arizona Green Tea Lemonade can', 'Arizona Green Tea Bangle', 'Cangles', '', 0),
(58, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/110.jpg', 'product=110+-+bracelet+-+Cara+Cuff+Bracelet&amp;price=18', '$18.00 ', 'Handmade with recycled magazines by women in Northern Uganda', 'Cara Cuff Bracelet', 'Not for Sale', '', 0),
(59, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/111.jpg', 'product=111+-+bracelet+-+Starbucks+Double+Shot+Espresso+Logo+Cuff&amp;price=18.95', '$18.95 ', 'Recycled Starbucks Double Shot Espresso & Cream  can', 'Starbucks Double Shot Espresso Logo Cuff', 'Cangles', '', 0),
(60, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/122.jpg', 'product=122+-+bracelet+-+Shahardzad+Bracelet&amp;price=18.99', '$18.99 ', 'Strands of Persian style beads fasten with an ornate clasp', 'Shahardzad Bracelet', 'Night Light', '', 0),
(61, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/123.jpg', 'product=123+-+bracelet+-+Kiran+Bracelet&amp;price=21.99', '$21.99 ', 'Variegated beads in orange, blue and gold spiral together', 'Kiran Bracelet', 'Night Light', '', 0),
(62, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/114.jpg', 'product=114+-+bracelet+-+Grape+Soda+Weave+Bangle&amp;price=34.95', '$34.95 ', 'Recycled strips from a Grape Soda can weaved into a bracelet', 'Grape Soda Weave Bangle', 'Cangles', '', 0),
(63, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/115.jpg', 'product=115+-+bracelet+-+Silver+and+Black+Weave+Bangle&amp;price=34.95', '$34.95 ', 'Bangle is handmade by recycling Arizona Green Tea Lemonade can', 'Silver and Black Weave Bangle', 'Cangles', '', 0),
(64, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/126.jpg', 'product=126+-+bracelet+-+Two+Toned+Pearl+Bracelet&amp;price=34.99', '$34.99 ', 'The vivid shades of aqua and sea blue freshwater pearls intertwined', 'Two Toned Pearl Bracelet', 'Night Light', '', 0),
(65, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/128.jpg', 'product=128+-+bracelet+-+Snow+Blossom+Bracelet&amp;price=36.99', '$36.99 ', 'Freshwater pearls, sparkling clear crystals, and white mountain jade', 'Snow Blossom Bracelet', 'Night Light', '', 0),
(66, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/124.jpg', 'product=124+-+bracelet+-+Cleopatra+Coin+Bracelet&amp;price=42.99', '$42.99 ', 'Three strands of red jasper and golden beads', 'Cleopatra Coin Bracelet', 'Night Light', '', 0),
(67, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/125.jpg', 'product=125+-+bracelet+-+Onyx+Treasure+Box+Bracelet&amp;price=74.99', '$74.99 ', 'A stunning treasure trove of black onyx, laborite, Swarovski crystals', 'Onyx Treasure Box Bracelet', 'Night Light', '', 0),
(68, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/127.jpg', 'product=127+-+bracelet+-+Reflection+Bracelet&amp;price=78.99', '$78.99 ', 'Freshwater pearls, sparkling clear crystals, and white mountain jade', 'Reflection Bracelet', 'Night Light', '', 0),
(69, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/118.jpg', 'product=118+-+bracelet+-+Crossword+Pizzle+Handmade+Bead+Bracelet&amp;price=79', '$79.00 ', 'Recycled Newspaper Crossword Puzzle Beads on an  elastic cord', 'Crossword Pizzle Handmade Bead Bracelet', 'Newspaper Jewelry', '', 0),
(70, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/119.jpg', 'product=119+-+bracelet+-+Comic+Strip+Handmade+Bracelet&amp;price=79', '$79.00 ', 'Recycled newspaper crossword puzzle beads on an elastic band', 'Comic Strip Handmade Bracelet', 'Newspaper Jewelry', '', 0),
(71, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/121.jpg', 'product=121+-+bracelet+-+Expired+Coupons+with+Bracelet&amp;price=99', '$99.00 ', 'Recycled Expired Coupons with Silver-plated Bead Trim', 'Expired Coupons with Bracelet', 'Newspaper Jewelry', '', 0),
(72, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/156.jpg', 'product=156+-+bracelet+-+Victoria+Double+Bracelet&amp;price=125', '$125.00 ', 'Silver & Gold Plated Metal on Black Leather, Taupe Leather', 'Victoria Double Bracelet', 'Shawn Warren', '', 0),
(73, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/139.jpg', 'product=139+-+bracelet+-+Two-Toned+Mix+Link+Bracelet&amp;price=125', '$125.00 ', 'Size: 7-1/2”. Combines sterling silver links with larger gold plated links', 'Two-Toned Mix Link Bracelet', 'Charity Charms', '', 0),
(74, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/138.jpg', 'product=138+-+bracelet+-+Gratitude+Ball+Bracelet&amp;price=130', '$130.00 ', 'Size: 8” . Comes with mini signature logo charm ', 'Gratitude Ball Bracelet', 'Charity Charms', '', 0),
(75, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/153.jpg', 'product=153+-+bracelet+-+Victoria+Single+Bracelet+Black+and++Gold&amp;price=150', '$150.00 ', 'Black Swarovski Crystals with Gold Dipped Metal on Black Leather.  ', 'Victoria Single Bracelet Black and  Gold', 'Shawn Warren', '', 0),
(76, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/154.jpg', 'product=154+-+bracelet+-+Victoria+Single+Bracelet+Black+and+Silver&amp;price=150', '$150.00 ', 'Black Swarovski Crystal with Silver and Gunmetal on Black Leather', 'Victoria Single Bracelet Black and Silver', 'Shawn Warren', '', 0),
(77, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/155.jpg', 'product=155+-+bracelet+-+Victoria+Single+Bracelet+Neon&amp;price=150', '$150.00 ', 'Gunmetal and Pink Metal on Neon Yellow Leather', 'Victoria Single Bracelet Neon', 'Shawn Warren', '', 0),
(78, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/157.jpg', 'product=157+-+bracelet+-+Victoria+Single+Bracelet+Navy&amp;price=150', '$150.00 ', 'Blue Swarovski Crystals on Silver and Gunmetal on Navy Leather.', 'Victoria Single Bracelet Navy', 'Shawn Warren', '', 0),
(79, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/140.jpg', 'product=140+-+bracelet+-+Affirmation+Bracelet&amp;price=165', '$165.00 ', 'words of encouragement: Peace, Courage, Strength, Passion, Harmony', 'Affirmation Bracelet', 'Charity Charms', '', 0),
(80, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/120.jpg', 'product=120+-+bracelet+-+Comic+Strips+with+Sterling+Silver+Trim+Bracelet&amp;price=239', '$239.00 ', 'This unique eco bracelet consists of recycled newspaper comic strips.', 'Comic Strips with Sterling Silver Trim Bracelet', 'Newspaper Jewelry', '', 0),
(81, '0000-00-00', '', 'bracelet', 'images/Product/100_Bracelets/109.jpg', 'product=109+-+bracelet+-+Three+Slim+Bracelet&amp;price=650', '$650.00 ', 'Set of three slim bangle. All in Sterling Silver', 'Three Slim Bracelet', 'John Hardy', '', 0),
(82, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/301.jpg', 'product=301+-+earring+-+Cleopatra+Teardrop+Earrings&amp;price=22.99', '$22.99 ', 'Red jasper and gold colored beads draped in sophisticated teardrop', 'Cleopatra Teardrop Earrings', 'Night Light', '', 0),
(83, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/302.jpg', 'product=302+-+earring+-+Arizona+Teas+Large+Flower+Earrings&amp;price=9.95', '$9.95 ', 'Handmade by recycling an Arizona Green Tea can', 'Arizona Teas Large Flower Earrings', 'Cangles', '', 0),
(84, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/303.jpg', 'product=303+-+earring+-+Fresca+Large+Flower+Earrings&amp;price=9.95', '$9.95 ', 'Handmade by recycling Fresca soft drink cans', 'Fresca Large Flower Earrings', 'Cangles', '', 0),
(85, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/304.jpg', 'product=304+-+earring+-+Fruit+Punch+Large+Flower+Earrings&amp;price=9.95', '$9.95 ', 'Handmade by recycling  Arizona  fruit punch cans', 'Fruit Punch Large Flower Earrings', 'Cangles', '', 0),
(86, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/305.jpg', 'product=305+-+earring+-+Musana+Earrings&amp;price=16', '$16.00 ', 'A cluster of beads hanging from a sterling sliver earring hook', 'Musana Earrings', 'Bead for Life', '', 0),
(87, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/306.1.jpg', 'product=306+-+earring+-+Single+Earring&amp;price=10', '$10.00 ', 'One paper bead hangs suspended from a string of beads', 'Single Earring', 'Bead for Life', '', 0),
(88, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/307.jpg', 'product=307+-+earring+-+Triple+Earring&amp;price=20', '$20.00 ', 'A three tired design created from a small, slender paper beads', 'Triple Earring', 'Bead for Life', '', 0),
(89, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/308.jpg', 'product=308+-+earring+-+Round+Stud+Earrings&amp;price=395', '$395.00 ', 'All in Sterling Silver', 'Round Stud Earrings', 'John Hardy', '', 0),
(90, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/309.jpg', 'product=309+-+earring+-+Jardin+Pear+Earrings+Gold&amp;price=395', '$395.00 ', 'Clip-on. Swarovski Crystal set in yellow Plated Brass', 'Jardin Pear Earrings Gold', 'Shawn Warren', '', 0),
(91, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/310.jpg', 'product=310+-+earring+-+Jardin+Pear+Earrings+Silver&amp;price=395', '$395.00 ', 'Clip-on. Swarovski Crystals set in Black Rhodium Plated Brass', 'Jardin Pear Earrings Silver', 'Shawn Warren', 'yes', 0),
(92, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/311.jpg', 'product=311+-+earring+-+Elyse+Open+Pear+Drop+Earrings&amp;price=2200', '$2,200.00 ', 'Amazonite and Diamonds set in Silver with Pink Gold plating', 'Elyse Open Pear Drop Earrings', 'Shawn Warren', '', 0),
(93, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/312.jpg', 'product=312+-+earring+-+Jardin+Leaf+Earrings+Gold&amp;price=295', '$295.00 ', 'Clip-on. Swarovski Crystals set in Yellow Plated Brass', 'Jardin Leaf Earrings Gold', 'Shawn Warren', '', 0),
(94, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/313.jpg', 'product=313+-+earring+-+Jardin+Leaf+Earrings+Black&amp;price=295', '$295.00 ', 'Clip-on. Swarovski Crystals set in Black Rhodium Plated Brass', 'Jardin Leaf Earrings Black', 'Shawn Warren', '', 0),
(95, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/314.jpg', 'product=314+-+earring+-+Libby+Small+Flex+Earrings+Blue&amp;price=1750', '$1,750.00 ', 'Blue Sapphires set in 18K White Gold with Black Rhodium ', 'Libby Small Flex Earrings Blue', 'Shawn Warren', '', 0),
(96, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/315.jpg', 'product=315+-+earring+-+Libby+Small+Flex+Earrings+Green&amp;price=1750', '$1,750.00 ', 'Tsavorite set in 18K White Gold with Black Rhodium ', 'Libby Small Flex Earrings Green', 'Shawn Warren', '', 0),
(97, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/316.jpg', 'product=316+-+earring+-+Libby+Small+Flex+Earrings+Pink&amp;price=1750', '$1,750.00 ', 'Pink Sapphires set in 18K White Gold with Black Rhodium', 'Libby Small Flex Earrings Pink', 'Shawn Warren', 'Pin', 0),
(98, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/317.jpg', 'product=317+-+earring+-+Libby+Small+Flex+Earrings+Black&amp;price=1750', '$1,750.00 ', 'Black Diamonds set in 18K White Gold with Black Rhodium', 'Libby Small Flex Earrings Black', 'Shawn Warren', '', 0),
(99, '0000-00-00', '', 'earring', 'images/Product/300_Earrings/318.jpg', 'product=318+-+earring+-+Libby+Small+Flex+Earrings+Pink+Saphire+and+White+Gold&amp;price=1750', '$1,750.00 ', 'Pink Sapphires set in 18K White Gold', 'Libby Small Flex Earrings Pink Saphire and White Gold', 'Shawn Warren', '', 0),
(100, '0000-00-00', '', 'charm', 'images/Product/200_Charms/201.jpg', 'product=201+-+charm+-+Black+Awareness+Ribbon&amp;price=40', '$40.00 ', 'sterling silver, symbol of mourning, melanoma, and gang prevention ', 'Black Awareness Ribbon', 'Charity Charms', '', 0),
(101, '0000-00-00', '', 'charm', 'images/Product/200_Charms/202.jpg', 'product=202+-+charm+-+Green+Awareness+Ribbon&amp;price=40', '$40.00 ', 'sterling silver charm, symbol of mental health and children safety ', 'Green Awareness Ribbon', 'Charity Charms', '', 0),
(102, '0000-00-00', '', 'charm', 'images/Product/200_Charms/203.jpg', 'product=203+-+charm+-+Orange+Awareness+Ribbon&amp;price=40', '$40.00 ', 'sterling silver, symbol of leukemia, cultural diversity, and self-injury', 'Orange Awareness Ribbon', 'Charity Charms', '', 0),
(103, '0000-00-00', '', 'charm', 'images/Product/200_Charms/204.jpg', 'product=204+-+charm+-+Pink+Awareness+Ribbon&amp;price=40', '$40.00 ', 'sterling silver, symbol of breast cancer, birth parent, childhood cancer ', 'Pink Awareness Ribbon', 'Charity Charms', '', 0),
(104, '0000-00-00', '', 'charm', 'images/Product/200_Charms/205.jpg', 'product=205+-+charm+-+Purple+Awareness+Ribbon&amp;price=40', '$40.00 ', 'sterling silver, symbol of pancreatic cancer, ADD and animal abuse ', 'Purple Awareness Ribbon', 'Charity Charms', '', 0),
(105, '0000-00-00', '', 'charm', 'images/Product/200_Charms/206.jpg', 'product=206+-+charm+-+Red+Awareness+Ribbon&amp;price=40', '$40.00 ', 'sterling silver, symbol of heart disease, stroke, MADD, and DARE', 'Red Awareness Ribbon', 'Charity Charms', '', 0),
(106, '0000-00-00', '', 'charm', 'images/Product/200_Charms/207.jpg', 'product=207+-+charm+-+Silver+Awareness+Ribbon&amp;price=40', '$40.00 ', 'sterling silver, symbol of disabled children and Parkinson’s disease', 'Silver Awareness Ribbon', 'Charity Charms', '', 0),
(107, '0000-00-00', '', 'charm', 'images/Product/200_Charms/208.jpg', 'product=208+-+charm+-+Yellow+Awareness+Ribbon&amp;price=40', '$40.00 ', 'sterling silver, symbol of our troops, MIA/POW and suicide prevention', 'Yellow Awareness Ribbon', 'Charity Charms', '', 0),
(108, '0000-00-00', '', 'charm', 'images/Product/200_Charms/209.jpg', 'product=209+-+charm+-+Catholic+Charities&amp;price=50', '$50.00 ', 'sterling silver, work with individuals, families, and communities ', 'Catholic Charities', 'Charity Charms', '', 0),
(109, '0000-00-00', '', 'charm', 'images/Product/200_Charms/210.jpg', 'product=210+-+charm+-+Child+Crisis+Center&amp;price=50', '$50.00 ', 'sterling silver, physical, emotional, educational and spiritual needs ', 'Child Crisis Center', 'Charity Charms', '', 0),
(110, '0000-00-00', '', 'charm', 'images/Product/200_Charms/211.jpg', 'product=211+-+charm+-+Child+Help&amp;price=50', '$50.00 ', 'sterling silver, increases awareness for children in need ', 'Child Help', 'Charity Charms', '', 0),
(111, '0000-00-00', '', 'charm', 'images/Product/200_Charms/212.jpg', 'product=212+-+charm+-+Gabriels+Angles&amp;price=50', '$50.00 ', 'sterling silver, mission to deliver therapy to abused or a neglected child', 'Gabriels Angles', 'Charity Charms', '', 0),
(112, '0000-00-00', '', 'charm', 'images/Product/200_Charms/213.jpg', 'product=213+-+charm+-+Sojourner+Center&amp;price=50', '$50.00 ', 'sterling silver, awareness for the domestic violence shelter ', 'Sojourner Center', 'Charity Charms', '', 0),
(113, '0000-00-00', '', 'charm', 'images/Product/200_Charms/214.jpg', 'product=214+-+charm+-+ACT&amp;price=50', '$50.00 ', 'sterling silver, funding for Autism Care and Treatment', 'ACT', 'Charity Charms', '', 0),
(114, '0000-00-00', '', 'charm', 'images/Product/200_Charms/215.jpg', 'product=215+-+charm+-+PEO&amp;price=50', '$50.00 ', 'sterling silver, awareness for celebration of women', 'PEO', 'Charity Charms', '', 0),
(115, '0000-00-00', '', 'charm', 'images/Product/200_Charms/216.jpg', 'product=216+-+charm+-+Ryan+House&amp;price=50', '$50.00 ', 'sterling silver, spreads awareness  of Ryan House', 'Ryan House', 'Charity Charms', '', 0),
(116, '0000-00-00', '', 'charm', 'images/Product/200_Charms/217.jpg', 'product=217+-+charm+-+St+Mary''s+Food+Bank&amp;price=50', '$50.00 ', 'sterling silver, elimination of hunger ', 'St Mary''s Food Bank', 'Charity Charms', 'yes', 0),
(117, '0000-00-00', '', 'charm', 'images/Product/200_Charms/218.jpg', 'product=218+-+charm+-+Fresh+Start&amp;price=50', '$50.00 ', 'sterling silver, awareness for Fresh Start Women’s Foundation', 'Fresh Start', 'Charity Charms', '', 0),
(118, '0000-00-00', '', 'charm', 'images/Product/200_Charms/219.jpg', 'product=219+-+charm+-+Sun+Devil+Swimming+Association&amp;price=50', '$50.00 ', 'sterling silver, awareness of financial viability of ASU Swimming', 'Sun Devil Swimming Association', 'Charity Charms', '', 0),
(119, '0000-00-00', '', 'charm', 'images/Product/200_Charms/220.jpg', 'product=220+-+charm+-+American+Heart+Association&amp;price=50', '$50.00 ', 'sterling silver, awareness of American Heart Association', 'American Heart Association', 'Charity Charms', '', 0),
(120, '0000-00-00', '', 'charm', 'images/Product/200_Charms/221.jpg', 'product=221+-+charm+-+American+Lung+Association&amp;price=50', '$50.00 ', 'sterling silver, awareness for American Lung Association', 'American Lung Association', 'Charity Charms', '', 0),
(121, '0000-00-00', '', 'charm', 'images/Product/200_Charms/222.jpg', 'product=222+-+charm+-+Arthritis+Foundation&amp;price=50', '$50.00 ', 'sterling silver, awareness for Arthritis Foundation', 'Arthritis Foundation', 'Charity Charms', '', 0),
(122, '0000-00-00', '', 'charm', 'images/Product/200_Charms/223.jpg', 'product=223+-+charm+-+Cystic+Fibrosis&amp;price=50', '$50.00 ', 'sterling silver, awareness for Cystic Foundation', 'Cystic Fibrosis', 'Charity Charms', '', 0),
(123, '0000-00-00', '', 'charm', 'images/Product/200_Charms/224.jpg', 'product=224+-+charm+-+Friends+of+the+Orphans&amp;price=50', '$50.00 ', 'sterling silver, awareness of giving safety and bright future to orphans', 'Friends of the Orphans', 'Charity Charms', '', 0),
(124, '0000-00-00', '', 'charm', 'images/Product/200_Charms/225.jpg', 'product=225+-+charm+-+Special+Olympics&amp;price=50', '$50.00 ', 'sterling silver, awareness for a global nonprofit organization of disabled', 'Special Olympics', 'Charity Charms', '', 0),
(125, '0000-00-00', '', 'charm', 'images/Product/200_Charms/226.jpg', 'product=226+-+charm+-+Centers+for+Habilitation&amp;price=50', '$50.00 ', 'sterling silver, awareness for empowering those with disabilities', 'Centers for Habilitation', 'Charity Charms', '', 0),
(126, '0000-00-00', '', 'charm', 'images/Product/200_Charms/227.jpg', 'product=227+-+charm+-+Goodwill&amp;price=50', '$50.00 ', 'sterling silver, awareness of the work of Goodwill', 'Goodwill', 'Charity Charms', '', 0),
(127, '0000-00-00', '', 'charm', 'images/Product/200_Charms/228.jpg', 'product=228+-+charm+-+SARRC&amp;price=50', '$50.00 ', 'sterling silver, awareness to advance research for support of autism  ', 'SARRC', 'Charity Charms', '', 0),
(128, '0000-00-00', '', 'charm', 'images/Product/200_Charms/229.jpg', 'product=229+-+charm+-+Steele+Children''s+Research+Center&amp;price=50', '$50.00 ', 'sterling silver, awareness of Steel Children’s Research Center ', 'Steele Children''s Research Center', 'Charity Charms', '', 0),
(129, '0000-00-00', '', 'charm', 'images/Product/200_Charms/230.jpg', 'product=230+-+charm+-+Arizona+Humane+Society+Cat&amp;price=50', '$50.00 ', 'sterling silver, spreads awareness for the AHS and their cause', 'Arizona Humane Society Cat', 'Charity Charms', '', 0),
(130, '0000-00-00', '', 'charm', 'images/Product/200_Charms/231.jpg', 'product=231+-+charm+-+Arizona+Humane+Society+Dog&amp;price=50', '$50.00 ', 'sterling silver, spreads awareness for the AHS and their cause', 'Arizona Humane Society Dog', 'Charity Charms', '', 0),
(131, '0000-00-00', '', 'charm', 'images/Product/200_Charms/232.jpg', 'product=232+-+charm+-+Arizona+Humane+Society+Heart+Paw&amp;price=50', '$50.00 ', 'sterling silver, awareness for AHS and their cause', 'Arizona Humane Society Heart Paw', 'Charity Charms', '', 0),
(132, '0000-00-00', '', 'charm', 'images/Product/200_Charms/233.jpg', 'product=233+-+charm+-+Charity+Charms+Logo+Charm&amp;price=40', '$40.00 ', 'sterling silver', 'Charity Charms Logo Charm', 'Charity Charms', '', 0),
(133, '0000-00-00', '', 'charm', 'images/Product/200_Charms/234.jpg', 'product=234+-+charm+-+Cross+Symbol+Charm&amp;price=40', '$40.00 ', 'sterling silver, symbol for sacrifice and eternal life', 'Cross Symbol Charm', 'Charity Charms', '', 0),
(134, '0000-00-00', '', 'charm', 'images/Product/200_Charms/235.jpg', 'product=235+-+charm+-+Arizona''s+Children+Association&amp;price=50', '$50.00 ', 'sterling silver, awareness of Arizona’s Children Association', 'Arizona''s Children Association', 'Charity Charms', '', 0),
(135, '0000-00-00', '', 'charm', 'images/Product/200_Charms/236.jpg', 'product=236+-+charm+-+Circle+L+Ranch&amp;price=50', '$50.00 ', 'sterling silver, awareness to find loving homes for adoptable animals', 'Circle L Ranch', 'Charity Charms', '', 0),
(136, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/401.jpg', 'product=401.1+-+Elastic+Headbands+#1+Blue+White+and+Orange&amp;price=10', '$10.00 ', 'Textile design, features 2 inch elastic, covered in fabric', 'Elastic Headbands #1 Blue White and Orange', 'Project Have Hope', '', 0),
(137, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/401.jpg', 'product=401.2+-+Elastic+Headbands+#2+Green+and+Black&amp;price=10', '$10.00 ', 'Textile design, features 2 inch elastic, covered in fabric', 'Elastic Headbands #2 Green and Black', 'Project Have Hope', '', 0),
(138, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/401.jpg', 'product=401.3+-+Elastic+Headbands+#3+Olive+Green+and+Blue&amp;price=10', '$10.00 ', 'Textile design, features 2 inch elastic, covered in fabric', 'Elastic Headbands #3 Olive Green and Blue', 'Project Have Hope', '', 0),
(139, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/401.jpg', 'product=401.4+-+Elastic+Headbands+#4+Orange+and+Yellow&amp;price=10', '$10.00 ', 'Textile design, features 2 inch elastic, covered in fabric', 'Elastic Headbands #4 Orange and Yellow', 'Project Have Hope', 'yes', 0),
(140, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/401.jpg', 'product=401.5+-+Elastic+Headbands+#5Bright+Green+and+Black&amp;price=10', '$10.00 ', 'Textile design, features 2 inch elastic, covered in fabric', 'Elastic Headbands #5Bright Green and Black', 'Project Have Hope', '', 0),
(141, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/401.jpg', 'product=401.6+-+Elastic+Headbands+#6+Turqoise+Blue+and+Black&amp;price=10', '$10.00 ', 'Textile design, features 2 inch elastic, covered in fabric', 'Elastic Headbands #6 Turqoise Blue and Black', 'Project Have Hope', '', 0),
(142, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=401.1+-+Elastic+Headbands+#1+Blue+White+and+Orange&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #1 Teal', 'Project Have Hope', '', 0),
(143, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.2+-+Tie+Headbands+#2+Blue+and+White&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #2 Blue and White', 'Project Have Hope', '', 0),
(144, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.3+-+Tie+Headbands+#3+Olive+Green+and+Black&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #3 Olive Green and Black', 'Project Have Hope', '', 0),
(145, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.4+-+Tie+Headbands+#4+Blue+Green+and+White&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #4 Blue Green and White', 'Project Have Hope', '', 0),
(146, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.5+-+Tie+Headbands+#5+Green+and+Yellow&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #5 Green and Yellow', 'Project Have Hope', '', 0),
(147, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.6+-+Tie+Headbands+#6+Green+and+Black&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #6 Green and Black', 'Project Have Hope', '', 0),
(148, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.7+-+Tie+Headbands+#7+Teal+and+Brown&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #7 Teal and Brown', 'Project Have Hope', '', 0),
(149, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.8+-+Tie+Headbands+#8+Orange&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #8 Orange', 'Project Have Hope', '', 0),
(150, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.9+-+Tie+Headbands+#9+Turquoise+and+Black&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #9 Turquoise and Black', 'Project Have Hope', '', 0),
(151, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.10.+-+Tie+Headbands+#10+Blue+and+Black+&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #10 Blue and Black ', 'Project Have Hope', '', 0),
(152, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.11+-+Tie+Headbands+#11+Purple&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #11 Purple', 'Project Have Hope', '', 0),
(153, '0000-00-00', '', 'headband', 'images/Product/400_Headbands/402.jpg', 'product=402.12+-+Tie+Headbands+#12+Orange+and+Yellow&amp;price=10', '$10.00 ', 'Bright, African textiles are used to create a tie style headband', 'Tie Headbands #12 Orange and Yellow', 'Project Have Hope', '', 0),
(154, '0000-00-00', '', 'misc', 'images/Product/800_Misc_Accessory/801.jpg', 'product=801+-+Coin+Anklet&amp;price=10', '$10.00 ', 'The coin is an old East African coin that is stung on a card.', 'Coin Anklet', 'Project Have Hope', '', 0),
(155, '0000-00-00', '', 'misc', 'images/Product/800_Misc_Accessory/802.jpg', 'product=802.1+-+Kisa+Jewelry+Bag+Blue&amp;price=15', '$15.00 ', 'Cotton African fabric with accenting satin interior. Drawstring closure', 'Kisa Jewelry Bag Blue', 'Beads for Life', '', 0),
(156, '0000-00-00', '', 'misc', 'images/Product/800_Misc_Accessory/802.jpg', 'product=802.2+-+Kisa+Jewelry+Bag+Earthtone&amp;price=15', '$15.00 ', 'Cotton African fabric with accenting satin interior. Drawstring closure', 'Kisa Jewelry Bag Earthtone', 'Beads for Life', '', 0),
(157, '0000-00-00', '', 'misc', 'images/Product/800_Misc_Accessory/802.jpg', 'product=802.3+-+Kisa+Jewelry+Bag+Purple&amp;price=15', '$15.00 ', 'Cotton African fabric with accenting satin interior. Drawstring closure', 'Kisa Jewelry Bag Purple', 'Beads for Life', 'yes', 0),
(158, '0000-00-00', '', 'misc', 'images/Product/800_Misc_Accessory/802.jpg', 'product=802.4+-+Kisa+Jewelry+Bag+Pink&amp;price=15', '$15.00 ', 'Cotton African fabric with accenting satin interior. Drawstring closure', 'Kisa Jewelry Bag Pink', 'Beads for Life', '', 0),
(159, '0000-00-00', '', 'misc', 'images/Product/800_Misc_Accessory/802.jpg', 'product=802.5+-+Kisa+Jewelry+Bag+Red&amp;price=15', '$15.00 ', 'Cotton African fabric with accenting satin interior. Drawstring closure', 'Kisa Jewelry Bag Red', 'Beads for Life', '', 0),
(160, '0000-00-00', '', 'misc', 'images/Product/800_Misc_Accessory/802.jpg', 'product=802.6+-+Kisa+Jewelry+Bag+Black&amp;price=15', '$15.00 ', 'Cotton African fabric with accenting satin interior. Drawstring closure', 'Kisa Jewelry Bag Black', 'Beads for Life', '', 0),
(161, '0000-00-00', '', 'misc', 'images/Product/800_Misc_Accessory/802.jpg', 'product=802.7+-+Kisa+Jewelry+Bag+Green&amp;price=15', '$15.00 ', 'Cotton African fabric with accenting satin interior. Drawstring closure', 'Kisa Jewelry Bag Green', 'Beads for Life', '', 0),
(162, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/501.jpg', 'product=501+-+Giving+Key&amp;price=35', '$35.00 ', 'key pendant, helps transition out of homelessness', 'Giving Key', 'Not for Sale', 'yes', 0),
(163, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/502.jpg', 'product=502.1+-+Single+Strand+Necklace+dark+green&amp;price=10', '$10.00 ', 'recycled paper beads in vibrant colors', 'Single Strand Necklace dark green', 'Project Have Hope', '', 0),
(164, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/502.jpg', 'product=502.2+-+Single+Strand+Necklace+light+green&amp;price=10', '$10.00 ', 'recycled paper beads in vibrant colors', 'Single Strand Necklace light green', 'Project Have Hope', '', 0),
(165, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/502.jpg', 'product=502.3+-+Single+Strand+Necklace+yellow&amp;price=10', '$10.00 ', 'recycled paper beads in vibrant colors', 'Single Strand Necklace yellow', 'Project Have Hope', '', 0),
(166, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/502.jpg', 'product=502.4+-+Single+Strand+Necklace+orange&amp;price=10', '$10.00 ', 'recycled paper beads in vibrant colors', 'Single Strand Necklace orange', 'Project Have Hope', '', 0),
(167, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/502.jpg', 'product=502.5+-+Single+Strand+Necklace+red&amp;price=10', '$10.00 ', 'recycled paper beads in vibrant colors', 'Single Strand Necklace red', 'Project Have Hope', '', 0),
(168, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/502.jpg', 'product=502.6+-+Single+Strand+Necklace+light+blue&amp;price=10', '$10.00 ', 'recycled paper beads in vibrant colors', 'Single Strand Necklace light blue', 'Project Have Hope', '', 0),
(169, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/502.jpg', 'product=502.7+-+Single+Strand+Necklace+purple&amp;price=10', '$10.00 ', 'recycled paper beads in vibrant colors', 'Single Strand Necklace purple', 'Project Have Hope', '', 0),
(170, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/502.jpg', 'product=502.8+-+Single+Strand+Necklace+pink&amp;price=10', '$10.00 ', 'recycled paper beads in vibrant colors', 'Single Strand Necklace pink', 'Project Have Hope', '', 0),
(171, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/503.jpg', 'product=503+-+Coca-Cola+Square+Necklace&amp;price=13.25', '$13.25 ', 'eco-friendly', 'Coca-Cola Square Necklace', 'Cangles', '', 0),
(172, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/504.jpg', 'product=504+-+Brisk+Tea+Long+Pendant&amp;price=14.95', '$14.95 ', 'eco-friendly, long pendant handmade by recycling', 'Brisk Tea Long Pendant', 'Cangles', '', 0),
(173, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/505.jpg', 'product=505+-+Asaba+Triple+Swirl+Necklace&amp;price=20', '$20.00 ', 'paper beads strung on plastic line', 'Asaba Triple Swirl Necklace', 'Bead For Life', '', 0),
(174, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/505.jpg', 'product=505.1+-+Asaba+Triple+Swirl+Necklace&amp;price=20', '$20.00 ', 'paper beads strung on plastic line', 'Asaba Triple Swirl Necklace', 'Bead For Life', '', 0),
(175, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/506.jpg', 'product=506+-+Leena+Three+Strand+Necklace&amp;price=20', '$20.00 ', 'paper beads on plastic string, optional  colors: brown, green, purple, red', 'Leena Three Strand Necklace', 'Bead For Life', '', 0),
(176, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/507.jpg', 'product=507+-+Sanyu+Single+Short+Necklace&amp;price=13', '$13.00 ', 'handmade paper beads, colors: green, purple, red, white, blue', 'Sanyu Single Short Necklace', 'Bead For Life', '', 0),
(177, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/508.jpg', 'product=508+-+Sanyu+Sinlge+Long+Necklace&amp;price=18', '$18.00 ', 'handmade paper beads on durable plastic line', 'Sanyu Sinlge Long Necklace', 'Bead For Life', '', 0),
(178, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/509.jpg', 'product=509+-+Moyo+Five+Strand+Necklace+Green&amp;price=30', '$30.00 ', 'Paper beads strung onto durable plastic line, elongated beads', 'Moyo Five Strand Necklace Green', 'Bead For Life', '', 0),
(179, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/509.1.jpg', 'product=509.1+-+Moyo+Five+Strand+Necklace+Red&amp;price=30', '$30.00 ', 'Paper beads strung onto durable plastic line, elongated beads', 'Moyo Five Strand Necklace Red', 'Bead For Life', '', 0),
(180, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/510.jpg', 'product=510+-+Black+Whistle+&amp;price=54', '$54.00 ', 'represents oppression of the enslaved human race ', 'Black Whistle ', 'Falling whistle', '', 0),
(181, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/511.jpg', 'product=511+-+Gun+Metal&amp;price=44', '$44.00 ', 'worn and weathered', 'Gun Metal', 'Falling whistle', '', 0),
(184, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/514.jpg', 'product=514+-+Unisex+Necklace+&amp;+Map+of+Africa+Pendant&amp;price=99', '$99.00 ', 'map of Africa pendant', 'Unisex Necklace & Map of Africa Pendant', 'Hands for Africa', '', 0),
(185, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/515.jpg', 'product=515+-+14K+Gold+Plated+Unisex+Necklace+&amp;+Map+of+Africa+Pendant&amp;price=99', '$99.00 ', 'map of Africa pendant ', '14K Gold Plated Unisex Necklace & Map of Africa Pendant', 'Hands for Africa', '', 0),
(186, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/516.jpg', 'product=516+-+Amputee+Crafted+Beaded+Necklace+w/map+of+Sierra+Leone&amp;price=25', '$25.00 ', 'handcrafted unisex beaded necklace', 'Amputee Crafted Beaded Necklace w/map of Sierra Leone', 'Hands for Africa', '', 0),
(187, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/517.jpg', 'product=517+-+5.56mm+Classic+Bullet+Necklace&amp;price=19.99', '$19.99 ', '5.56mm hand pressed bullet necklace', '5.56mm Classic Bullet Necklace', 'Bullets 2 Bandages', '', 0),
(188, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/518.jpg', 'product=518+-+5.56mm+Tiger+Bronze+Bullet+Necklace+and+Dog+Tag&amp;price=29.99', '$29.99 ', '5.56mm hand pressed bullet necklace', '5.56mm Tiger Bronze Bullet Necklace and Dog Tag', 'Bullets 2 Bandages', '', 0),
(189, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/519.jpg', 'product=519+-+7.62+Classic+Bullet+Necklace+and+Dog+Tag&amp;price=19.99', '$19.99 ', '7.62mm hand pressed bullet necklace', '7.62 Classic Bullet Necklace and Dog Tag', 'Bullets 2 Bandages', '', 0),
(190, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/520.jpg', 'product=520+-+7.62+Classic+Bullet+Skinny+Chain+Necklace&amp;price=19.99', '$19.99 ', '7.62mm hand pressed bullet necklace', '7.62 Classic Bullet Skinny Chain Necklace', 'Bullets 2 Bandages', '', 0),
(191, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/521.jpg', 'product=521+-+7.62+Tiger+Bronze+Bullet+Necklace+and+Dog+Tag&amp;price=29.99', '$29.99 ', '7.62mm hand pressed bullet necklace', '7.62 Tiger Bronze Bullet Necklace and Dog Tag', 'Bullets 2 Bandages', '', 0),
(192, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/522.jpg', 'product=522+-+7.62+Tiger+Bronze+Bullet+Skinny+Chain+Necklace&amp;price=29.99', '$29.99 ', '5.56mm hand pressed bullet necklace', '7.62 Tiger Bronze Bullet Skinny Chain Necklace', 'Bullets 2 Bandages', '', 0),
(193, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/523.jpg', 'product=523+-+Round+Pendant&amp;price=225', '$225.00 ', 'round pendant with blue topaz, sterling silver and 18K Gold', 'Round Pendant', 'John Hardy', '', 0),
(194, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/524.jpg', 'product=524+-+18+K+White+Gold+Heart+Diamond+Pendants&amp;price=995', '$995.00 ', 'diamond heart pendant, pave-set diamonds ', '18 K White Gold Heart Diamond Pendants', 'Brilliant Earth', '', 0),
(195, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/525.jpg', 'product=525+-+18+K+White+Infinity+Pendants&amp;price=125', '$125.00 ', 'delicate infinity pendant, delicate cable chain', '18 K White Infinity Pendants', 'Brilliant Earth', '', 0),
(196, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/526.jpg', 'product=526+-+18+K+White+Gold+Three+Diamond+Drop+Pendants&amp;price=1275', '$1,275.00 ', 'round diamond, classic four-prong pendant ', '18 K White Gold Three Diamond Drop Pendants', 'Brilliant Earth', '', 0),
(197, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/527.jpg', 'product=527+-+18+K+White+Gold+Four-+Prong+Diamond+Pendent&amp;price=975', '$975.00 ', 'round diamond, classic four-prong pendant', '18 K White Gold Four- Prong Diamond Pendent', 'Brilliant Earth', '', 0),
(198, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/528.jpg', 'product=528+-+Original+Whistle&amp;price=34', '$34.00 ', 'symbol of protest ', 'Original Whistle', 'Falling whistle', '', 0),
(199, '0000-00-00', '', 'necklace', 'images/Product/500_Necklaces/529.jpg', 'product=529+-+Moyo+Five+Strand+Necklace+Red&amp;price=30', '$30.00 ', '', 'Moyo Five Strand Necklace Red', 'Bead For Life', '', 0),
(202, '0000-00-00', '', 'ring', 'images/Product/600_Rings/601.jpg', 'product=601+-+Not+For+Sale&amp;price=45', '$45.00 ', 'hand crafted silvery jewelry', 'Not For Sale', 'Not For Sale', '', 0),
(203, '0000-00-00', '', 'ring', 'images/Product/600_Rings/606.jpg', 'product=606+-+Small+Round+Ring&amp;price=350', '$350.00 ', 'All in Sterling Silver. ', 'Small Round Ring', 'John Hardy', '', 0),
(204, '0000-00-00', '', 'ring', 'images/Product/600_Rings/602.jpg', 'product=602+-+Long+Saddle+Ring&amp;price=695', '$695.00 ', 'John Hardy, All in Sterling Silver & 18K Gold. ', 'Long Saddle Ring', 'John Hardy', '', 0),
(205, '0000-00-00', '', 'ring', 'images/Product/600_Rings/612.jpg', 'product=612+-+Small+Oval+Ring+Blue&amp;price=695', '$695.00 ', 'sterling silver, John Hardy', 'Small Oval Ring Blue', 'John Hardy', '', 0),
(206, '0000-00-00', '', 'ring', 'images/Product/600_Rings/603.jpg', 'product=603+-+Small+Oval+Ring+Pink&amp;price=995', '$995.00 ', 'John Hardy,  All in Sterling Silver', 'Small Oval Ring Pink', 'John Hardy', '', 0),
(207, '0000-00-00', '', 'ring', 'images/Product/600_Rings/607.jpg', 'product=607+-+Rectangular+Ring&amp;price=995', '$995.00 ', '(0.32ct). All in Sterling Silver. ', 'Rectangular Ring', 'John Hardy', '', 0),
(208, '0000-00-00', '', 'ring', 'images/Product/600_Rings/609.jpg', 'product=609+-+Dome+Ring+White&amp;price=1195', '$1,195.00 ', 'sterling silver, Hematite and Black Spinel, John Hardy', 'Dome Ring White', 'John Hardy', '', 0),
(209, '0000-00-00', '', 'ring', 'images/Product/600_Rings/610.jpg', 'product=610+-+Dome+Ring+Black&amp;price=1195', '$1,195.00 ', 'sterling silver, Hematite and Black Spinel, John Hardy', 'Dome Ring Black', 'John Hardy', '', 0),
(210, '0000-00-00', '', 'ring', 'images/Product/600_Rings/611.jpg', 'product=611+-+Dome+Ring+Orange&amp;price=1195', '$1,195.00 ', 'sterling silver, Hematite and Spinel, John Hardy', 'Dome Ring Orange', 'John Hardy', '', 0),
(211, '0000-00-00', '', 'ring', 'images/Product/600_Rings/608.jpg', 'product=608+-+Dome+Ring+Sky+Blue&amp;price=1295', '$1,295.00 ', 'sterling silver, Hematite and Black Spinel, John Hardy', 'Dome Ring Sky Blue', 'John Hardy', '', 0),
(212, '0000-00-00', '', 'ring', 'images/Product/600_Rings/605.jpg', 'product=605+-+Round+Ring&amp;price=1495', '$1,495.00 ', 'John Hardy,  All in Sterling Silver & 18K Gold ', 'Round Ring', 'John Hardy', '', 0),
(213, '0000-00-00', '', 'ring', 'images/Product/600_Rings/614.jpg', 'product=614+-+Disco+Crossover+Ring&amp;price=1800', '$1,800.00 ', 'Assorted Color Diamonds set in Pink Plated Silver, Shawn Warren', 'Disco Crossover Ring', 'Shawn Warren', 'yes', 0),
(214, '0000-00-00', '', 'ring', 'images/Product/600_Rings/613.jpg', 'product=613+-+Starry+Night+Ring&amp;price=1950', '$1,950.00 ', 'Amethyst set in 18k Yellow Gold, Shawn Warren', 'Starry Night Ring', 'Shawn Warren', '', 0),
(215, '0000-00-00', '', 'ring', 'images/Product/600_Rings/604.jpg', 'product=604+-+Two+Finger+Ring&amp;price=1995', '$1,995.00 ', 'Amethyst and Swiss Blue Topaz. All in Sterling Silver & 18K Gold ', 'Two Finger Ring', 'John Hardy', '', 0),
(216, '0000-00-00', '', 'watch', 'images/Product/700_Watches/713.jpg', 'product=713+-+Interchangeable+Light+Blue&amp;price=40', '$40.00 ', 'Interchangeable, Large Analog Face, and Lightweight', 'Interchangeable Light Blue', 'Flex Watches', '', 0),
(217, '0000-00-00', '', 'watch', 'images/Product/700_Watches/714.jpg', 'product=714+-+Interchangeable+Grey&amp;price=40', '$40.00 ', 'Interchangeable, Large Analog Face, and Lightweight', 'Interchangeable Grey', 'Flex Watches', '', 0),
(218, '0000-00-00', '', 'watch', 'images/Product/700_Watches/715.jpg', 'product=715+-+Interchangeable+Black+and+White&amp;price=40', '$40.00 ', 'Interchangeable, Large Analog Face, Lightweight', 'Interchangeable Black and White', 'Flex Watches', '', 0),
(219, '0000-00-00', '', 'watch', 'images/Product/700_Watches/716.jpg', 'product=716+-+Interchangeable+Black&amp;price=40', '$40.00 ', 'Interchangeable, Large Analog Face, Lightweight', 'Interchangeable Black', 'Flex Watches', '', 0);
INSERT INTO `jewelry` (`id`, `date`, `gender`, `type`, `image`, `cart`, `price`, `description`, `title`, `charity`, `promo`, `note`) VALUES
(220, '0000-00-00', '', 'watch', 'images/Product/700_Watches/717.jpg', 'product=717+-+Interchangeable+White&amp;price=40', '$40.00 ', 'Interchangeable, Large Analog Face, Lightweight', 'Interchangeable White', 'Flex Watches', '', 0),
(221, '0000-00-00', '', 'watch', 'images/Product/700_Watches/718.jpg', 'product=718+-+Interchangeable+Orange&amp;price=40', '$40.00 ', 'Interchangeable , Large Analog Face, Lightweight', 'Interchangeable Orange', 'Flex Watches', '', 0),
(222, '0000-00-00', '', 'watch', 'images/Product/700_Watches/719.jpg', 'product=719+-+Interchangeable+Yellow&amp;price=40', '$40.00 ', 'Interchangeable , Large Analog Face, Lightweight', 'Interchangeable Yellow', 'Flex Watches', '', 0),
(223, '0000-00-00', '', 'watch', 'images/Product/700_Watches/720.jpg', 'product=720+-+Interchangeable+Purple&amp;price=40', '$40.00 ', 'Interchangeable , Large Analog Face, Lightweight', 'Interchangeable Purple', 'Flex Watches', '', 0),
(224, '0000-00-00', '', 'watch', 'images/Product/700_Watches/721.jpg', 'product=721+-+Interchangeable+Pink&amp;price=40', '$40.00 ', 'Interchangeable , Large Analog Face, Lightweight', 'Interchangeable Pink', 'Flex Watches', '', 0),
(225, '0000-00-00', '', 'watch', 'images/Product/700_Watches/722.jpg', 'product=722+-+Interchangeable+Green&amp;price=40', '$40.00 ', 'Interchangeable , Large Analog Face, Lightweight', 'Interchangeable Green', 'Flex Watches', '', 0),
(226, '0000-00-00', '', 'watch', 'images/Product/700_Watches/723.jpg', 'product=723+-+Interchangeable+Dark+Blue&amp;price=40', '$40.00 ', 'Interchangeable , Large Analog Face, Lightweight', 'Interchangeable Dark Blue', 'Flex Watches', '', 0),
(227, '0000-00-00', '', 'watch', 'images/Product/700_Watches/724.jpg', 'product=724+-+Interchangeable+Red&amp;price=40', '$40.00 ', 'Interchangeable , Large Analog Face, Lightweight', 'Interchangeable Red', 'Flex Watches', '', 0),
(228, '0000-00-00', '', 'watch', 'images/Product/700_Watches/701.jpg', 'product=701+-+Date+Brown+Army&amp;price=120', '$120.00 ', '100% wood, Hypo-allergenic, Miyota movement', 'Date Brown Army', 'WeWood', '', 0),
(229, '0000-00-00', '', 'watch', 'images/Product/700_Watches/702.jpg', 'product=702+-+Date+Army&amp;price=120', '$120.00 ', 'Guaiaco is a tree from South America. Its  said to help heal pain', 'Date Army', 'WeWood', '', 0),
(230, '0000-00-00', '', 'watch', 'images/Product/700_Watches/703.jpg', 'product=703+-+Date+Chocolate+&amp;price=120', '$120.00 ', 'Strong and heavy. Used for chess sets and billiard cues', 'Date Chocolate ', 'WeWood', '', 0),
(231, '0000-00-00', '', 'watch', 'images/Product/700_Watches/704.jpg', 'product=704+-+Moon+Beige&amp;price=120', '$120.00 ', 'The wood of this tree is often used to  make musical instruments', 'Moon Beige', 'WeWood', '', 0),
(232, '0000-00-00', '', 'watch', 'images/Product/700_Watches/709.jpg', 'product=709+-+Date+Beige&amp;price=120', '$120.00 ', 'The wood of this tree is often used to make musical instruments', 'Date Beige', 'WeWood', '', 0),
(233, '0000-00-00', '', 'watch', 'images/Product/700_Watches/710.jpg', 'product=710+-+Date+Brown+&amp;price=120', '$120.00 ', 'This tree is often used for flooring', 'Date Brown ', 'WeWood', '', 0),
(234, '0000-00-00', '', 'watch', 'images/Product/700_Watches/711.jpg', 'product=711+-+Date+Black&amp;price=120', '$120.00 ', 'Blackwood is easily worked and very stable and long lasting', 'Date Black', 'WeWood', '', 0),
(235, '0000-00-00', '', 'watch', 'images/Product/700_Watches/712.jpg', 'product=712+-+Date+Beige/Brown&amp;price=120', '$120.00 ', 'consists of maple and oak wood ', 'Date Beige/Brown', 'WeWood', '', 0),
(236, '0000-00-00', '', 'watch', 'images/Product/700_Watches/705.jpg', 'product=705+-+Jupiter+Black&amp;price=139', '$139.00 ', 'Blackwood is easily worked and very stable and long lasting', 'Jupiter Black', 'WeWood', '', 0),
(237, '0000-00-00', '', 'watch', 'images/Product/700_Watches/706.jpg', 'product=706+-+Jupiter+Beige&amp;price=139', '$139.00 ', 'The wood of this tree is often used to make musical instruments', 'Jupiter Beige', 'WeWood', 'yes', 0),
(238, '0000-00-00', '', 'watch', 'images/Product/700_Watches/707.jpg', 'product=707+-+Jupiter+Brown&amp;price=139', '$139.00 ', 'This tree is often used for flooring ', 'Jupiter Brown', 'WeWood', '', 0),
(239, '0000-00-00', '', 'watch', 'images/Product/700_Watches/708.jpg', 'product=708+-+Jupiter+Army&amp;price=139', '$139.00 ', 'Guaiaco is a tree from South America. Its said to help heal pain', 'Jupiter Army', 'WeWood', '', 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
